export type BusinessErrorCode =
  // Trips
  | 'PASSENGER_HAS_ACTIVE_TRIP'
  | 'DRIVER_HAS_ACTIVE_TRIP'
  | 'INVALID_TRIP_TRANSITION'
  | 'TRIP_NOT_FOUND'
  // Auth
  | 'PHONE_ALREADY_REGISTERED'
  | 'PHONE_BANNED'
  | 'USER_NOT_FOUND'
  | 'USER_SUSPENDED'
  | 'OTP_INVALID'
  | 'OTP_EXPIRED'
  | 'TOKEN_INVALID'
  | 'TOKEN_EXPIRED'
  // Drivers
  | 'DRIVER_ALREADY_REGISTERED'
  | 'DRIVER_NOT_APPROVED'
  | 'DOCUMENTS_EXPIRED'
  | 'DRIVER_NOT_FOUND'
  | 'DRIVER_OFFLINE'
  | 'NO_ACTIVE_VEHICLE'
  | 'REQUIREMENT_NOT_FOUND'
  | 'VEHICLE_PLATE_DUPLICATE'
  | 'DOCUMENT_NOT_FOUND'
  // Payments
  | 'PAYMENT_NOT_FOUND'
  | 'PAYMENT_ALREADY_PROCESSED'
  | 'TRIP_NOT_CHARGEABLE'
  | 'NO_PAYMENT_METHOD'
  // Pricing
  | 'FARE_BELOW_MINIMUM'
  | 'TRIP_TYPE_NOT_FOUND'
  | 'ORIGIN_EQUALS_DESTINATION'
  | 'DISTANCE_EXCEEDS_LIMIT'
  // Trip stacking
  | 'DRIVER_TRIP_QUEUE_FULL'
  | 'DRIVER_NOT_NEAR_COMPLETION'
  // Trip lifecycle
  | 'NOT_AUTHORIZED_FOR_TRANSITION'
  | 'TRIP_NOT_IN_SEARCHING'
  | 'TRIP_NOT_IN_PROGRESS'
  | 'TRIP_CANNOT_BE_CANCELLED'
  | 'ONLY_PASSENGER_CAN_CHANGE_DESTINATION'
  // Scheduled trips
  | 'SCHEDULED_TOO_SOON'
  | 'TRIP_NOT_SCHEDULED'
  // Custody
  | 'TRIP_NOT_ACTIVE'
  // Approval flow
  | 'DRIVER_NOT_AVAILABLE'
  // Temperature
  | 'INVALID_TEMPERATURE'
  // Admin
  | 'INVALID_CREDENTIALS'
  | 'ADMIN_ERROR_NOT_FOUND'
  | 'ADMIN_ERROR_ALREADY_RESOLVED'
  | 'FACTOR_NOT_FOUND'
  | 'INVALID_FEE_PCT'
  | 'COMMISSION_NOT_FOUND'
  // Verticals
  | 'VERTICAL_NOT_FOUND'
  // Companies
  | 'COMPANY_NOT_FOUND'
  | 'COMPANY_SLUG_TAKEN'
  | 'USER_ALREADY_IN_COMPANY'
  | 'COMPANY_USER_NOT_FOUND'
  // Configurations
  | 'CONFIG_NOT_FOUND'
  | 'INVALID_ENTITY_TYPE'
  // General
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'VALIDATION_ERROR'
  // Custody — multi-tenant
  | 'TENANT_REQUIRED'
  // Custody Orders
  | 'ORDER_NOT_FOUND'
  | 'INVALID_ORDER_TRANSITION'
  // Clients
  | 'CLIENT_NOT_FOUND'
  | 'CLIENT_ALREADY_EXISTS'
  // Operadores
  | 'OPERATOR_NOT_FOUND'
  | 'OPERATOR_ALREADY_EXISTS'
  | 'OPERATOR_SUSPENDED'
  | 'OPERATOR_ON_ACTIVE_ORDER'
  | 'INVALID_OPERATOR_TYPE'
  // Vehicles
  | 'VEHICLE_NOT_FOUND'
  | 'PLATE_ALREADY_EXISTS'
  // Value declarations
  | 'VALUE_DECLARATION_NOT_FOUND'
  | 'CUSTODY_TYPE_NOT_FOUND'
  // Custody tracking
  | 'ORDER_NOT_TRACKABLE'
  | 'OPERATOR_NOT_ASSIGNED'
  | 'NO_LOCATION_DATA'
  // Security alerts
  | 'ALERT_NOT_FOUND'
  | 'ALERT_ALREADY_RESOLVED'
  | 'PANIC_ALERT_TOO_SOON'
  | 'ORDER_NOT_ACTIVE_FOR_ALERT'
  | 'ONLY_SUPERVISOR_CAN_RESOLVE_CRITICAL'
  // Custody payments
  | 'INVALID_ORDER_STATUS_FOR_PAYMENT';

const STATUS_CODE_MAP: Record<BusinessErrorCode, number> = {
  PASSENGER_HAS_ACTIVE_TRIP: 409,
  DRIVER_HAS_ACTIVE_TRIP: 409,
  DRIVER_TRIP_QUEUE_FULL: 409,
  DRIVER_NOT_NEAR_COMPLETION: 409,
  INVALID_TRIP_TRANSITION: 409,
  TRIP_NOT_FOUND: 404,
  PHONE_ALREADY_REGISTERED: 409,
  PHONE_BANNED: 403,
  USER_NOT_FOUND: 404,
  USER_SUSPENDED: 403,
  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  TOKEN_INVALID: 401,
  TOKEN_EXPIRED: 401,
  DRIVER_ALREADY_REGISTERED: 409,
  DRIVER_NOT_APPROVED: 403,
  DOCUMENTS_EXPIRED: 403,
  DRIVER_NOT_FOUND: 404,
  DRIVER_OFFLINE: 403,
  NO_ACTIVE_VEHICLE: 403,
  REQUIREMENT_NOT_FOUND: 404,
  VEHICLE_PLATE_DUPLICATE: 409,
  DOCUMENT_NOT_FOUND: 404,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_ALREADY_PROCESSED: 409,
  TRIP_NOT_CHARGEABLE: 422,
  NO_PAYMENT_METHOD: 422,
  FARE_BELOW_MINIMUM: 422,
  TRIP_TYPE_NOT_FOUND: 404,
  ORIGIN_EQUALS_DESTINATION: 422,
  DISTANCE_EXCEEDS_LIMIT: 422,
  NOT_AUTHORIZED_FOR_TRANSITION: 403,
  TRIP_NOT_IN_SEARCHING: 409,
  TRIP_NOT_IN_PROGRESS: 409,
  TRIP_CANNOT_BE_CANCELLED: 409,
  ONLY_PASSENGER_CAN_CHANGE_DESTINATION: 403,
  SCHEDULED_TOO_SOON: 400,
  TRIP_NOT_SCHEDULED: 409,
  TRIP_NOT_ACTIVE: 409,
  DRIVER_NOT_AVAILABLE: 409,
  INVALID_TEMPERATURE: 400,
  INVALID_CREDENTIALS: 401,
  ADMIN_ERROR_NOT_FOUND: 404,
  ADMIN_ERROR_ALREADY_RESOLVED: 409,
  FACTOR_NOT_FOUND: 404,
  INVALID_FEE_PCT: 422,
  COMMISSION_NOT_FOUND: 404,
  VERTICAL_NOT_FOUND: 400,
  COMPANY_NOT_FOUND: 404,
  COMPANY_SLUG_TAKEN: 409,
  USER_ALREADY_IN_COMPANY: 409,
  COMPANY_USER_NOT_FOUND: 404,
  CONFIG_NOT_FOUND: 404,
  INVALID_ENTITY_TYPE: 422,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  VALIDATION_ERROR: 422,
  TENANT_REQUIRED: 403,
  ORDER_NOT_FOUND: 404,
  INVALID_ORDER_TRANSITION: 409,
  CLIENT_NOT_FOUND: 404,
  CLIENT_ALREADY_EXISTS: 409,
  OPERATOR_NOT_FOUND: 404,
  OPERATOR_ALREADY_EXISTS: 409,
  OPERATOR_SUSPENDED: 422,
  OPERATOR_ON_ACTIVE_ORDER: 422,
  INVALID_OPERATOR_TYPE: 400,
  VEHICLE_NOT_FOUND: 404,
  PLATE_ALREADY_EXISTS: 409,
  VALUE_DECLARATION_NOT_FOUND: 404,
  CUSTODY_TYPE_NOT_FOUND: 404,
  ORDER_NOT_TRACKABLE: 409,
  OPERATOR_NOT_ASSIGNED: 403,
  NO_LOCATION_DATA: 404,
  ALERT_NOT_FOUND: 404,
  ALERT_ALREADY_RESOLVED: 409,
  PANIC_ALERT_TOO_SOON: 409,
  ORDER_NOT_ACTIVE_FOR_ALERT: 409,
  ONLY_SUPERVISOR_CAN_RESOLVE_CRITICAL: 403,
  INVALID_ORDER_STATUS_FOR_PAYMENT: 409,
};

export class BusinessError extends Error {
  public readonly code: BusinessErrorCode;
  public readonly statusCode: number;

  constructor(code: BusinessErrorCode, message?: string) {
    super(message ?? code);
    this.name = 'BusinessError';
    this.code = code;
    this.statusCode = STATUS_CODE_MAP[code];
  }
}
